name: Docker Container CD

on:
    pull_request:
        paths:
            - 'backend-printing/**'
            - '.github/workflows/cd.yaml'
            
    workflow_dispatch:

permissions:
    id-token: write
    contents: read
    pull-requests: read

jobs:
    CD:
        uses: ./.github/workflows/shared-flow.yaml
        with:
            imagePush: true
        secrets:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_PLATFORM_SUBSCRIPTION_ID }}
