name: SAP Background Printing Container flow

on:
  workflow_call: 
    inputs:
     imagePush:
      type: boolean
      required: false
      default: false
    secrets:
      AZURE_TENANT_ID:
        required: true
        description: 'Azure Tenant ID'
      AZURE_CLIENT_ID:
        required: true
        description: 'Azure Client ID'
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: 'Azure Subscription ID'

jobs:
  shared:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: azure login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true

        - name: ACR login
          id: acrLogin
          run: |
            ACR_TOKEN=$(az acr login --name computeaksacr --expose-token --output tsv --query accessToken)
            echo "ACR_TOKEN=$ACR_TOKEN" >> $GITHUB_OUTPUT
            az acr login --name computeaksacr

        - name: compute environment variables
          run: |
            echo "IMAGE_REPOSITORY=computeaksacr.azurecr.io/bgprinting" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV

        - name: build active
          run: docker build -f ./backend-printing/Dockerfile -t $IMAGE_REPOSITORY:$IMAGE_TAG ./backend-printing

        - name: push
          if: ${{ inputs.imagePush }}
          run: |
            echo "${{ steps.acrLogin.outputs.ACR_TOKEN }}" | docker login computeaksacr.azurecr.io --username "00000000-0000-0000-0000-000000000000" --password-stdin
            docker push $IMAGE_REPOSITORY:$IMAGE_TAG

         